### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by davbe** [dahu/vim-help#1]
Hi !

I've installed vim-help but no mapping works. What could I possibly do wrong ? Is there anything I should do that I haven't thought of ?

Thanks,

David

**Comment by dahu** [comment]
The maps only work inside a :help window.

**Comment by davbe** [comment]
Of course, I'm aware of that.

When I hit s or S in a help window, I get the following message :

E21: Cannot make changes, 'modifiable' is off

I should mention I'm running Vim 7.4 on Windows x64.

**Comment by dahu** [comment]
The normal S command deletes the current line and starts inserting at the indentation point. Help files are not modifiable, so they give E21 when you try to modify a help buffer. SO... it seems that vim-help is not installed properly. How did you install the plugin?

**Comment by davbe** [comment]
I downloaded the zip file from the github repo and unzipped it in the "bundle" directory (pathogen).

:help vim-help works though.

**Comment by dahu** [comment]
So now you have paths like:

```
~/.vim/bundle/vim-help/ftplugin/help.vim
~/.vim/bundle/vim-help/plugin/help.vim
```

**Comment by davbe** [comment]
Yes I do. Well, to be precise, under Windows it is more like :

```
~/vimfiles/bundle/vim-help/ftplugin/help.vim
~/vimfiles/bundle/vim-help/plugin/help.vim
```

**Comment by dahu** [comment]
Oh... right... ftplugin...
Make sure your vimrc has a line like:

```
filetype plugin indent on
```

**Comment by davbe** [comment]
Thank you! It's working now :)

Now I can use your plugin to easily crawl through the help so that I can find out what the "filetype plugin indent on" line means :)

**Comment by dahu** [comment]
:-) glad to hear it. You might also like my other plugin, https://github.com/dahu/LearnVim

**Comment by davbe** [comment]
I do know LearnVim, I know vim-help thanks to it. I'm adventurous :)
